apiVersion: v1
kind: Service
metadata:
  name: tutum-hello-world
spec:
  selector:
    app: tutum-hello-world
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum-hello-world-deployment
  labels:
    app: tutum-hello-world
spec:
  selector:
    matchLabels:
      app: tutum-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: tutum-hello-world
    spec:
      containers:
      - name: tutum-hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80