name: Get services descriptions

on:

  workflow_dispatch:
    inputs:
  
  push:
    #protection to avoid triggering when other workflow is modified
    paths: 
    - '!.github/workflows/**'
    - '.github/workflows/aws-services.yml' 

jobs:
  access-services-pricing-descriptions:
    name: Access services pricing descriptions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #not all regions provide pricing
        aws-region: us-east-1
        
    - name: Install v2 and check aws CLI version
      # Github currently (Aug 2020) runs on aws CLI v1
      run: |-
        curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
        export AWS_VERSION=$(aws --version)
        echo "AWS_VERSION: $AWS_VERSION)"
        grep -q "aws-cli/2." <<< $AWS_VERSION

    - name: Describe services pricing and do checks
      # https://stackoverflow.com/questions/58028283/could-not-connect-to-the-endpoint-url-https-api-pricing-us-west-2-amazonaws
      run: |-
        export DESCRIBE_SERVICES=$(aws pricing describe-services)
        echo "describe-services: $DESCRIBE_SERVICES"
        grep '"ServiceCode": "AWSLambda"' <<< $DESCRIBE_SERVICES
        grep '"ServiceCode": "AmazonCloudFront"' <<< $DESCRIBE_SERVICES
        
    - name: Get EC2 attributes
      run: |-
        export EC2_ATTRIBUTES=$(aws pricing get-attribute-values --service-code 'AmazonEC2' --attribute-name 'volumeType' )
        echo "ec2 attributes: $EC2_ATTRIBUTES"
        grep '"Value": "General Purpose"' <<< $EC2_ATTRIBUTES
        grep '"Value": "Magnetic"' <<< $EC2_ATTRIBUTES